nominal:
  goal:
    coordinates:
      - 1.75
      - 1.75
      - 0
    padding:
      - 0.05
      - 0.05
      - 0.5
    max_time: 30.0
    time_intervals: 101
    solver_accuracy: "high"
  frequency: 20.0
cbf:
  gamma: 0.2