dynamics_class: "dubins_car"
safe_set:
  lo: 
    - -5.0
    - -5.0
    - -3.1416
  hi: 
    - 5.0
    - 5.0
    - 3.1416

obstacles: 
  
  obstacle1:
    type: 'Circle'
    mode: 'Detection'
    indices:
      - 0
      - 1
    center: 
      - 1.5
      - 1.5
    radius: 1
    padding: .1
    detectionradius: .5

  obstacle2:
    type: 'Rectangle'
    mode: 'Detection'
    indices:
      - 0
      - 1
    minVal:
      - -4.0
      - -4.0
    maxVal:
      - -3.0
      - -3.0
    padding: .1
    detectionradius: .5

  obstacle3:
    type: 'Circle'
    mode: 'Service'
    indices:
      - 0
      - 1
    center:
      - -1.0
      - 0.0
    radius: .1
    padding: .1

  obstacle4:
    type: 'Circle'
    mode: 'Update'
    indices:
      - 0
      - 1
    center:
      - 0.0
      - -1.0
    radius: .1
    padding: .1
    updatetime: 5

boundary:
  padding: 0
  indices:
    - 0
    - 1
  minVal:
    - -5.0
    - -5.0
  maxVal:
    - 10.0
    - 10.0

obstacle_update_rate_hz: 5

state_domain:
  lo: 
    - -5.0
    - -5.0
    - -3.1416
  hi: 
    - 10.0
    - 10.0
    - 3.1416
  resolution:
    - 41
    - 41
    - 41
  periodic_dims: [2]

control_space:
  n_dims: 2
  lo:
    - -1.0
    - 0.0
  hi: 
    - 1.0
    - 0.2

disturbance_space:
  n_dims: 0
  lo: None
  hi: None
